/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fuzzy.doner;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class BaseLineTest {
    @Test void baseLineAppHasAGreeting() {
        BaseLineApp classUnderTest = new BaseLineApp();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
