/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fuzzy.doner;

public class BaseLineApp {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new BaseLineApp().getGreeting());
    }
}
